### ISSUE TITLE
es6 Typescript Project

### ISSUE THREAD

**Issue by nnance** [raml-org/raml-js-parser-2#365] opened 2016-07-20 18:25 UTC
I am importing the raml parser into a TypeScript project that I have and I am setting the target to es6.  As a result I am getting the following error:

```
node_modules/raml-1-parser/typings/main/ambient/es6-promise/es6-promise.d.ts(12,15): error TS2300: Duplicate identifier 'Promise'.
node_modules/raml-1-parser/typings/main/ambient/es6-promise/es6-promise.d.ts(42,16): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(4796,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5119,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5286,13): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5504,11): error TS2300: Duplicate identifier 'Promise'.
```

Any ideas on how to resolve this? @blakeembrey

**Comment by blakeembrey** [comment] 2016-07-20 18:37
@nnance I do not work on this project.

That said, it's caused by duplicate identifiers as the issue says. You're using ES6 promises and this project has custom definitions referenced (E.g. https://github.com/raml-org/raml-js-parser-2/blob/master/src/Opt.ts#L1). The project would need to be fixed to avoid using references to custom internal definitions and should use `typings.json` dependencies (not globals).

**Comment by nnance** [comment] 2016-07-21 05:23
@blakeembrey I really appreciate the you taking time to provide feedback.  Sorry, I didn't realize you are not working on the project.

**Comment by sichvoge** [comment] 2016-07-21 15:37
@blakeembrey good to still hear from you :P we will look at this as one of the enhancements we will do. Thanks for clarifying that Blake ;)

**Comment by nnance** [comment] 2016-07-22 04:47
@sichvoge I have figured out what the exact fix is to make it work for both es6 and es5 typescript projects.  Would you be open to a PR?

**Comment by menduz** [comment] 2016-07-22 21:19
Same here. Indeed a blocker. @ddenisenko

**Comment by sichvoge** [comment] 2016-07-22 21:56
Yes, please send a PR! We will look at that.

**Comment by ddenisenko** [comment] 2016-09-15 03:25
Closing as implemented.

**Closed by ddenisenko** 2016-09-15 03:25 UTC
Labels: enhancement, Minor
