### ISSUE TITLE
parser 1.0.0 not expanding traits from extended file

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#437] opened 2016-09-01 10:19 UTC
base.raml:
```
#%RAML 1.0

...

traits:
  secure:
    securedBy: oath2
```

api.raml:
```
#%RAML 1.0 Extension

extends: ./base.raml

/foo:
  is: [ secure ]
  get:
```

loader.js
```
let ast = await raml.loadApi('api.raml');
ast = ast.expand();
```

After expansion `foo` has no securedBy schemas. If I move the trait into api.raml it works. This used to work with older version of the parser, so this is a regression I assume.

**Comment by domarmstrong** [comment] 2016-09-01 10:29
Actually I've tracked this to being introduced in version `0.2.29` before that they are expanding correctly.

**Comment by sichvoge** [comment] 2016-09-01 10:30
Thanks @domarmstrong. Seems like a regression. @ddenisenko please take care of that.

**Comment by KonstantinSviridov** [comment] 2016-09-01 21:37
@sichvoge The issue is fixed in the "develop" branch

**Comment by ddenisenko** [comment] 2016-09-02 03:12
Note: it was not a regression.

**Closed by ddenisenko** 2016-09-02 03:12 UTC
Labels: bug, Major

**Comment by domarmstrong** [comment] 2016-09-02 06:15
Thanks guys
