### ISSUE TITLE
Official 'Applying Libraries' example does not parse

### ISSUE THREAD

**Issue by j-funk** [raml-org/raml-js-parser-2#118] opened 2016-04-20 21:05 UTC
I was having considerable trouble getting `uses` with `!include` to pass validation using `raml-js-parser-2`. I decided to take the example from the [official documentation](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#applying-libraries) and see if it passed validation. To my surprise the example throws errors when run through the parser.  It's possible I've made some errors or missed some assumptions in my interpretation of the example - I'm new to RAML.  Any feedback is appreciated!  

Here's [a repo](https://github.com/j-funk/raml-1.0-parser-test) to make it quick to diagnose / reproduce (or fix).

**Comment by j-funk** [comment] 2016-04-21 19:22
Opened a similar issue on the documentation since I suspect the examples are awry.

**Comment by sichvoge** [comment] 2016-04-22 08:47
I think we should leave that open ;) The issue is not specific to the spec, but rather the parser. I've modified your example a bit and it seems that there is only one bit left that is not working. 

So as in the issue you linked here, using the RC2 branch I made the following adjustments:

* using array for every `is`
* removed `libraries` path name from files.raml

After that, almost all worked with the rc2 branch except `is: [ files.drm ]`. The error only states that it does not know about `files.drm` which is strange. Removing that line fixes the issue.

**Comment by j-funk** [comment] 2016-04-25 15:00
That is the same conclusion that I came to as well using `rc1`.  Will keep an eye on this and continue when it's fixed, really appreciate you looking into this. Thx.

**Comment by sichvoge** [comment] 2016-04-25 15:01
You can try the rc2 branch that currently contains all RC2 features.

**Comment by petrochenko-pavel-a** [comment] 2016-04-27 17:31
pushed fix to RC2

**Closed by petrochenko-pavel-a** 2016-04-27 17:31 UTC
Labels: bug
