### ISSUE TITLE
RAML-parser is not able to parse external xsd

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#599] opened 2017-01-09 16:08 UTC
Having a xsd file that uses another xsd file, parser is not able to load the second xsd.
Check attached example.
[api (5).zip](https://github.com/raml-org/raml-js-parser-2/files/693942/api.5.zip)

**Comment by ddenisenko** [comment] 2017-01-10 03:42
Thank you for reporting it.

This ticket is a duplicate of https://github.com/raml-org/raml-js-parser-2/issues/589 , which in turn is a duplicate of https://github.com/raml-org/raml-js-parser-2/issues/580.

It is fixed and its fix should be published soon.

Closing this ticket as duplicate.

**Comment by nmarinel01** [comment] 2017-01-10 11:48
Ok ! Thanks !

**Comment by nmarinel01** [comment] 2017-01-23 15:08
Hi @ddenisenko !
I would like to reopen this issue since the attached example fails with release 1.1.13
Can you look at this again ?
Thanks !

**Comment by dreamflyer** [comment] 2017-01-25 02:30
@nmarinel01, everything looks fine for me, example is working. Please provide exact description of usage.

**Comment by ddenisenko** [comment] 2017-01-26 23:52
@nmarinel01 also please let us know how exactly you use the parser. Is it npm or web version? Do you use sync or async loading? Are your resources provided via http, file system, or custom file resolver / http resolver. Do you perform resource type/trait expansion and/or library expansion?

**Comment by nmarinel01** [comment] 2017-02-08 13:52
Hi Denis, 
We are using the web version, the method loadApi, via custom file resolver, with library expansion.

Now we have more detail about the problem:
The issue is that the parser is calling the custom fsResolver.content method instead of the contentAsync method, and in the Designer we can't always resolve file content right away, thats why we can only provide the contentAsync.

The fsResolver.content is only being called for the xsd file, probably when resolving the xsd from the xml it uses the fsResolver.content method and this seems to be the issue.

Regards

**Comment by ddenisenko** [comment] 2017-02-11 03:15
Thanks for analysis! 

It shouldn't call `content` if you are using the async version of RAML loading. We'll try reproducing locally.

**Comment by ddenisenko** [comment] 2017-02-11 03:23
@nmarinel01 Could you please check if you can still reproduce it in 1.1.14? It looks like something looking very similar was already spotted and fixed: https://github.com/raml-org/raml-js-parser-2/issues/621

**Comment by nmarinel01** [comment] 2017-02-13 18:18
Hi @ddenisenko !
I tried again with 1.1.14 and now the example works fine. No errors and example gets validated ok.
Thanks !!

**Comment by ddenisenko** [comment] 2017-02-14 12:21
Sounds good.

**Closed by ddenisenko** 2017-02-14 12:21 UTC
Labels: bug, Critical, waiting-for-response
