### ISSUE TITLE
Typings is deprecated

### ISSUE THREAD

**Issue by daniel-pedersen** [raml-org/raml-js-parser-2#782] opened 2017-08-09 15:55 UTC
Typings has been deprecated for TypeScript 2.0 and the repository is archived.

Also I can't get the browser version thing from the README to work, typings just outputs blank lines (no dependencies).

**Comment by KonstantinSviridov** [comment] 2017-09-29 17:41
Hi, @daniel-pedersen !

Right now the 'develop' branches set is upgraded to Typescript 2.5.2 and is free from the 'typings' dependency. This enhancement will be brought to 'master' and npm with the next release.

As for the browser version, the problem is that the parser expects some older version of 'typings'.
In the [instruction](https://github.com/raml-org/raml-js-parser-2#creating-standalone-browser-package) one should replace
```
npm install typings --global
```
by
```
npm install typings@0.8.1 --global
```

If you choose [setting up a development environment](https://github.com/raml-org/raml-js-parser-2#setting-up-parser-development-environment) in the 'develop' branches set, you do not have to install 'typings'. But, please, keep in mind that the `typesystem-ts` plugin has been renamed to `raml-typesystem` and instead of executing
```
rm -rf typesystem-ts
npm link typesystem-ts
```
you have to execute
```
rm -rf raml-typesystem
npm link raml-typesystem
```
(this inconsistency will be fixed in the next release)

Please, let us know if you have more problems with generating the browser version.

Regards,
Kosntantin

**Comment by KonstantinSviridov** [comment] 2017-09-29 17:51
The typescript 2.5.2 commit is https://github.com/raml-org/raml-js-parser-2/commit/417d28681e9b5c56cbd57a9614ce4b1874433343

**Closed** 2017-10-02 17:16 UTC
Labels: bug, enhancement
