### ISSUE TITLE
Support for JSON schema reference via `!include` function

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#804] opened 2017-11-27 18:37 UTC
This has been reported as an issue of the API console. 
Use case scenario is described here: https://support.mulesoft.com/s/ideas#087340000005wbTAAQ

Basically it says to support a statement like this: 
```
type: !include api-cdm-schemas.json#definitions/campaign-member
```

**Comment by KonstantinSviridov** [comment] 2017-11-30 14:20
Hi, @jarrodek !

The issue is fixed by the following commit: https://github.com/raml-org/raml-js-parser-2/commit/1b5078b5197936603c7fdc2ef616c22df9a8e81c

The fix will appear in the next release.

Regards,
Konstantin

**Closed by KonstantinSviridov** 2017-11-30 14:20 UTC
Labels: bug, jira
