### ISSUE TITLE
Fix JSON External type facets test 15

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#159] opened 2016-05-05 11:41 UTC
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: !include ./scheme.json

types:
  SchemaType:
    type: !include ./scheme.json
    displayName: test
    (TestAnnotation):
      name: "sdfdsf"
  TestType:
    type: object
  TestType2:
    type: object
    properties:
      testProp: !include ./scheme.json

```

should be invalid

**Comment by petrochenko-pavel-a** [comment] 2016-05-05 11:56
looks like another duplicate of #158

**Closed by petrochenko-pavel-a** 2016-05-05 11:56 UTC
Labels: bug, raml10-rc2
