### ISSUE TITLE
Error message for type related annotations should be more clear

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#768] opened 2017-06-23 10:14 UTC
Assume the following example:

```yaml
#%RAML 1.0 Library

types:
  test:
    (oas-schema-title): human
    properties:
      (oas-schema-title): human
      node:
        (oas-schema-title): human
        type: string

annotationTypes:
  oas-schema-title: 
    type: string
    allowedTargets: TypeDeclaration
```

The parser returns an error for the second use of `(oas-schema-title)` right under `properties` which states the following: `Property '(oas-schema-title)' refers to unknown type 'human'`.

What I would expect is that the parser tells me that I am not allowed to use the annotations inside the `properties` node. Right?

**Comment by KonstantinSviridov** [comment] 2017-06-27 15:10
Hi, Christian

In fact, the spec does not prohibit us from using bracket symbols in property names. Thus, what the parser sees, is property named "(oas-schema-title)" refering unknown type named "human". 

But we can modify existing error messages for those properties which have their names put into brackets. Instead of just
```
Property '(oas-schema-title)' refers to unknown type 'human'
```
we can produce
```
Invalid attempt to use 'oas-schema-title' annotation under the 'properties' key or property '(oas-schema-title)' refers to unknown type 'human'
```

But even in such case we will not catch case when type "human" is defined:
```
#%RAML 1.0 Library

types:
  human:
  test:
    (oas-schema-title): human
    properties:
      (oas-schema-title): human
      node:
        (oas-schema-title): human
        type: string

annotationTypes:
  oas-schema-title: 
    type: string
    allowedTargets: TypeDeclaration
```

**Comment by sichvoge** [comment] 2017-06-27 15:13
I see. We should really think about limiting the keys to a specific set of characters.

**Comment by KonstantinSviridov** [comment] 2017-06-27 15:18
I think, for now we can start produce warnings for all properties which have their names put into brackets.

**Comment by KonstantinSviridov** [comment] 2017-06-29 10:47
Let's assume that a property declaration "looks like annotation usage" if property name is put into brackets and property type is set by shortcut.
For example, this property declaration "looks like annotation usage":
```
properties:
  (prop): SomeType
```

and these do not:
```
properties:
  (prop1):
    type: SomeType

  (prop2: SomeType

  my(prop3): SomeType

  (my)prop4: SomeType

  prop5: SomeType
```

We can start producing warnings for all properties that "look like annotation usages" or modify error messages for those of them which refer unknown types.

**Comment by KonstantinSviridov** [comment] 2017-11-16 14:41
In fact,
```
 (prop1):
    type: SomeType
```
also looks like using some annotation like
```
MyAnnotationType:
  properties:
    type: string
```

**Comment by postatum** [comment] 2019-09-25 09:33
Closing for now as no answers. Feel free re-open if this is still relevant.

Note that raml-js-parser-2 has been deprecated, the new official parser is [webapi-parser](https://github.com/raml-org/webapi-parser). Feel free to attempt to reproduce this issue with webapi-parser and report any issue you may have on that repository.

**Closed by postatum** 2019-09-25 09:33 UTC
Labels: enhancement, jira, waiting-for-response
