### ISSUE TITLE
RAML parser resolves the !include of a YAML file as a string

### ISSUE THREAD

**Issue by pokraev** [raml-org/raml-js-parser-2#470] opened 2016-09-22 13:39 UTC
I have an API that includes examples from external file:

``` yaml
/sales-transactions:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/sales-transaction-created.sample.yaml
```

The `examples/sales-transaction-created.sample.yaml` has the folowing content:

``` yaml
message: "Sales Transaction successfully created"
```

I get as a result an example in yaml (which I think is incorrect):

``` yaml
message: "Sales Transaction successfully created"
```

If I do not use `!include` :

``` yaml
/sales-transactions:
  get:
    responses:
      200:
        body:
          application/json:
            example: 
              message: "Sales Transaction successfully created"
```

I get as a result an example in json (which I think is correct)

``` json
{
  "message": "Sales Transaction successfully created"
}
```

**Comment by eduardo-rubio** [comment] 2017-10-10 15:27
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#resolving-includes

**Comment by sichvoge** [comment] 2017-10-10 15:36
@eduardo-rubio can you elaborate how the link helps the OP to solve his issue? There is a difference between handling things as strings or YAML nodes.

**Comment by KonstantinSviridov** [comment] 2017-10-16 13:54
Hi, @pokraev !

The issue seems to be already fixed.

The 1.1.32 parser used in the following way
```js
var parser = require("raml-1-parser");
var path = require("path");

var apiPath = path.resolve(__dirname,"../RAML/api.raml");
parser.loadApi(apiPath, {
	attributeDefaults: false,
	rejectOnErrors: false
}).then(function (api) {
	api = api.expand();
			
  var json = api.toJSON({
  	serializeMetadata: false,
  	dumpSchemaContents: false,
  	rootNodeDetails: true
  });

  console.log(JSON.stringify(json,null,2));
},function(err){
  console.log(err);
});
```
 outputs
```json
{
  "ramlVersion": "RAML10",
  "type": "Api",
  "specification": {
    "title": "test API",
    "resources": [
      {
        "methods": [
          {
            "responses": {
              "200": {
                "code": "200",
                "body": {
                  "application/json": {
                    "name": "application/json",
                    "typePropertyKind": "INPLACE",
                    "example": {
                      "message": "Sales Transaction successfully created"
                    },
                    "structuredExample": {
                      "value": "{\n  \"message\": \"Sales Transaction successfully created\"\n}",
                      "strict": true,
                      "name": null,
                      "structuredValue": {
                        "message": "Sales Transaction successfully created"
                      }
                    }
                  }
                }
              }
            },
            "method": "get"
          }
        ],
        "relativeUri": "/sales-transactions",
        "relativeUriPathSegments": [
          "sales-transactions"
        ],
        "absoluteUri": "/sales-transactions"
      }
    ]
  },
  "errors": []
}
```
for your example.

Here is a simple example project which prints your example by the 1.1.32 parser:
[issue470.zip](https://github.com/raml-org/raml-js-parser-2/files/1387668/issue470.zip)

After unzipping one should call `npm install` and `npm run test`.

Please, let us know if you still face this problem.

Regards,
Konstantin

**Comment by postatum** [comment] 2019-09-25 09:31
Closing for now as no answers. Feel free to provide more information and re-open if this is still relevant

PS. Note that raml-js-parser-2 has been deprecated, the new official parser is [webapi-parser](https://github.com/raml-org/webapi-parser). Feel free to attempt to reproduce this issue with webapi-parser and report any issue you may have on that repository.

**Closed by postatum** 2019-09-25 09:31 UTC
Labels: enhancement, jira, waiting-for-response
