### ISSUE TITLE
No errors when schema is not compliant with draft-04 JSON schema

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#667] opened 2017-03-02 13:02 UTC
Having the following raml definition (attached) where replacement-schema is not compliant with draft-04 Json schema. Note that required attribute should be defined as array of strings.

No error is generated by parser to notify that schema is invalid. Just a warning at example level. Error should be informed

[api_schema_not_valid.raml.zip](https://github.com/raml-org/raml-js-parser-2/files/813825/api_schema_not_valid.raml.zip)

**Comment by ddenisenko** [comment] 2017-03-02 15:00
I guess it's a duplicate of https://github.com/raml-org/raml-js-parser-2/issues/623

Closing as duplicate.

Unfortunately, we are using 3-rd party validator for schemas so we are unsure if we can help with it.

**Closed** 2017-03-06 19:58 UTC
Labels: duplicate
