### ISSUE TITLE
Getting 'default' facet from runtimeType

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#600] opened 2017-01-09 17:26 UTC
Is there any way for me to get this, I would expect it to be available as part of allFixedFacets, but it doesn't seem to be. The spec describes these as facets, so I would expect to see them as facets:

default?
type?
displayName?
description?
enum?

I love raml, but the ast has a horrible api :(

I know I can get the default value from the typeDeclaration but I need to work with the runtimeType, due to other limitations. Can I maybe get the typeDeclaration from the runtimeType?

**Comment by ddenisenko** [comment] 2017-01-10 03:46
@domarmstrong allFixedFacets method returns only custom user facets, which were fixed. This is legacy caused by the fact that at the time of the method creation built-in facets you are listing simply did not exist (were not called "facets").

I do agree that this must be mentioned in the method description. I also think we should add a method to get fixed built-in facets (its better to avoid modifying allFixedFacets method behavior for compatibility).

We will try fitting this change in for the next release.

**Comment by KonstantinSviridov** [comment] 2017-01-12 23:04
Hi, @domarmstrong !

The issue is going to be fixed in 1.1.14. Right now the fix is only available in the `develop` brances set.

The fixed built in facet values will be available via the `fixetBuiltInFacets` and `allFixedBuiltInFacets` methods.
The `fixedBuiltInFacets` method will be returning values of facets fixed by the type itself, while `allFixedBuiltInFacets` will be returning values of facets fixed by the type and all of its supertypes.

Regards, Konstantin

**Closed by KonstantinSviridov** 2017-01-12 23:04 UTC
Labels: enhancement, Major
