### ISSUE TITLE
Invalid usage of custom facets

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#613] opened 2017-01-17 12:35 UTC
Please, look at the following example, where invalid definition and use of custom facets is being accepted without errors

```yaml
traits:
 pageSize:
   queryParameters:
     pageSize:
       facets:
         exclusiveMinimum: boolean
         exclusiveMaximum: boolean
       type: integer
       description: Number of persons returned
       format: int32
       maximum: 100
       default: 20
       exclusiveMinimum: true
       exclusiveMaximum: false
```

I understand this example should throw an error, as custom facets can be use when defined on a super / base type, through inheritance.

**Comment by KonstantinSviridov** [comment] 2017-01-20 19:12
Hi, @nmarinel01 

The issue is going to be fixed in 1.1.14

Regards, Konstantin

**Closed by KonstantinSviridov** 2017-01-20 19:12 UTC
Labels: bug
