### ISSUE TITLE
Shouldn't the parser expand the schema like it does with description?

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser-2#454] opened 2016-09-12 13:48 UTC
Using this example: https://github.com/raml-org/raml-examples/blob/master/others/world-music-api/api.raml.

```
resourceTypes:
  collection:
    get:
      description: returns a list of <<resourcePathName|!singularize>>
      responses:
        200:
          body:
            application/json:
              schema: <<resourcePathName|!singularize|!uppercamelcase>>
/entry:
  type:  collection
```

So the `/entry` resource is of type `collection` which defines a GET method. And indeed in the raml object the GET method is added to the `/entry` resource.

One weird problem with that. While the description for the GET method is expanded from `returns a list of <<resourcePathName|!singularize>>` to `returns a list of entry`, the schema of the body in the 200 response is not expanded at all. It's still `<<resourcePathName|!singularize|!uppercamelcase>>`. 

It seems logical to me that the raml parser would expand/translate this as well, like it does for the description?

**Comment by sichvoge** [comment] 2016-09-12 13:50
Seems to be related to https://github.com/raml-org/raml-js-parser-2/issues/446 but the issue is closed. @KonstantinSviridov can you explain?

**Comment by KonstantinSviridov** [comment] 2016-09-12 14:12
@sichvoge You're right, it's already fixed in the latest `hotfixes` branch.

**Closed** 2016-09-20 16:36 UTC
Labels: bug, Critical
