### ISSUE TITLE
Fix JSON External type facets test 17

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#161] opened 2016-05-05 11:43 UTC
RAML

```
#%RAML 1.0
title: "test"

annotationTypes:
  TestAnnotation: !include ./scheme.json

types:
  SchemaType:
    type: !include ./scheme.json
    displayName: test
    (TestAnnotation):
      name: "sdfdsf"
  TestType:
    type: object
  TestType2:
    type: object
    properties:
      testProp:
        type: !include ./scheme.json
        properties:
          name: string

```

is invalid, but instead of "property testProp range type has error: specifying unknown facet: properties" should say something like "It is not allowed to use external types in property definitions"

**Comment by petrochenko-pavel-a** [comment] 2016-05-05 11:56
so it is duplicate of #158

**Closed by petrochenko-pavel-a** 2016-05-05 11:56 UTC
Labels: bug, raml10-rc2
